# https://docs.sonarsource.com/sonarqube-server/latest/project-administration/setting-analysis-scope/introduction/
sonar.projectKey=z-wave-nvm-migration-tool

# --- optional properties ---

sonar.exclusions=build/,test*/**,zw_nvm_converter/nvm3lib/**
