# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025 Silicon Laboratories Inc. https://www.silabs.com
---
name: build

on:  # yamllint disable-line rule:truthy
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ${{ vars.RUNNER || 'ubuntu-24.04' }}
    env:
      SONAR_OUT_DIR: sonar
      build-dir: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install build dependencies
        run: |
          ./helper.mk setup

      - name: Install SonarQube Build Wrapper
        id: sonar-bw
        env:
          # yamllint disable rule:line-length
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL || 'https://sonarcloud.io'}}
          # yamllint disable rule:line-length
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@2500896589ef8f7247069a56136f8dc177c27ccf  # v5.2.0

      - name: Build project
        id: build
        run: >-
          set -x ;
          ./helper.mk
          SONAR_OUT_DIR="${{ env.SONAR_OUT_DIR }}"
          sonar_bw_app="${{env.build-wrapper-binary}}"
        env:
          build-wrapper-binary: ${{ steps.sonar-bw.outputs.build-wrapper-binary }}

      - name: Upload package artifacts
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          # yamllint disable-line rule:line-length
          name: ${{ github.event.repository.name }}-package
          path: ${{ env.build-dir }}/*.deb

      - name: SonarQube Scan
        # yamllint disable-line rule:line-length
        uses: sonarsource/sonarqube-scan-action@2500896589ef8f7247069a56136f8dc177c27ccf  # v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        if: ${{ env.SONAR_HOST_URL }}
        # yamllint disable rule:line-length
        with:
          args: >-
            --define sonar.cfamily.compile-commands="${{ env.SONAR_OUT_DIR}}/compile_commands.json"
            --define sonar.coverageReportPaths="${{ env.SONAR_OUT_DIR }}/coverage.xml"
        # yamllint enable rule:line-length

      - name: Upload analyze artifact
        if: steps.sonar-bw.outcome == 'success'
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          # yamllint disable-line
          name: ${{ github.event.repository.name }}-analyze
          path: |
            sonar-project.properties
            .scannerwork/report-task.txt
            ${{ env.SONAR_OUT_DIR }}
